import 'package:oprs/components/input/chip_selection_input.dart';
final List<String> subCityOptionsConstant = [
  "ADDIS KETEMA",
  "AKAKY KALITI",
  "ARADA",
  "BOLE",
  "GULELE",
  "KIRKOS",
  "KOLFE KERANIO",
  "LIDETA",
  "NIFAS SILK-LAFTO",
  "YEKA",
  "LEMI KURA"];
final Map<String, String> editListingInputErrorsConstant = {
  "title" : "",
  "description" : "",
  "ownerId" : "",
  "totalAreaSquareMeter" : "",
  "woreda" : "",
  "areaName" : "",
  "pricePerDuration" : "",
  "paymentCurrency" : "",
  "floorNumber" : "",
  "distanceFromRoadInMeters" : "",
  "leaseDurationDays" : "",
  "buildingName" : "",
  "taxResponsibility" : "",
  "storageCapacitySquareMeter" : ""
};
final List<SelectionChip> leaseDurationOptionsConstant = [
  SelectionChip("Daily", false),
  SelectionChip("Weekly", false),
  SelectionChip("Monthly", false),
];
final List<SelectionChip> warehouseOptionsConstant = [
  SelectionChip("Warehouse Unit",false),
  SelectionChip("Storage Unit",false),
  SelectionChip("Distribution Unit",false),
  SelectionChip("Warehouse Condo",false),
  SelectionChip("Storage Locker",false),
  SelectionChip("Retail Store",false),
];
final List<SelectionChip> eventOptionsConstant = [
  SelectionChip("Event Hall",false),
  SelectionChip("Ballroom",false),
  SelectionChip("Wedding hall", false),
  SelectionChip("Function Hall",false),
  SelectionChip("Meeting Venue",false),
  SelectionChip("Conference Hall",false),
  SelectionChip("Banquet Hall",false),
  SelectionChip("Events hall", false),
];
final List<SelectionChip> commercialOptionsConstant = [
  SelectionChip("Storefront",false),
  SelectionChip("Retail Space",false),
  SelectionChip("Office",false),
  SelectionChip("Business Premises",false),
  SelectionChip("Minimarket",false),
  SelectionChip("Supermarket",false),
  SelectionChip("Display",false),
  SelectionChip("Commercial Building",false),
  SelectionChip("Business Space",false),
];
final List<SelectionChip> residentalOptionsConstant = [
  SelectionChip("Mansion", false),
  SelectionChip("Apartment", false),
  SelectionChip("Condominium", false),
  SelectionChip("Villa", false),
  SelectionChip("Shared Room", false),
  SelectionChip("Room", false),
  SelectionChip("Flat", false),
  SelectionChip("Studio", false),
];
final List<SelectionChip> paymentCurrencyOptionsConstant = [
  SelectionChip("ETB", false),
  SelectionChip("USD", false),
  SelectionChip("EUR", false)
];
final List<SelectionChip> propertyCategoryOptionsConstant = [
  SelectionChip("RESIDENTAL", false),
  SelectionChip("COMMERCIAL", false),
  SelectionChip("STORAGE", false),
  SelectionChip("EVENT", false),
];
final List<SelectionChip> residentalAmenitiesConstant = [
  SelectionChip("Fire extinguisher", false),
  SelectionChip("First aid kit", false),
  SelectionChip("Elevator", false),
  SelectionChip("Key Card Access", false),
  SelectionChip("Electricity supply", false),
  SelectionChip("Swimming Pool", false),
  SelectionChip("Gym", false),
  SelectionChip("Bathtub", false),
  SelectionChip("Washing Machine", false),
  SelectionChip("Dish washer", false),
  SelectionChip("Sofa", false),
  SelectionChip("Tables", false),
  SelectionChip("Chairs", false),
  SelectionChip("Pillows", false),
  SelectionChip("TV", false),
  SelectionChip("Playgrounds", false),
  SelectionChip("Temprature control", false),
  SelectionChip("Burners", false),
  SelectionChip("Chairs", false),
  SelectionChip("Air conditioning", false),
  SelectionChip("Fireplace", false),
  SelectionChip("CCTV", false),
  SelectionChip("Wifi", false),
  SelectionChip("Refrigerator", false),
  SelectionChip("Oven", false),
  SelectionChip("Microwave", false),
  SelectionChip("Pans", false),
  SelectionChip("Dishes", false),
  SelectionChip("Silverware", false),
  SelectionChip("Stove", false),
  SelectionChip("Coffee maker", false),
  SelectionChip("Private entrance", false),
  SelectionChip("Emergency exit", false),
  SelectionChip("Balcony", false),
  SelectionChip("Pets allowed", false),
];
final List<SelectionChip> warehouseAmenitiesConstant = [
  SelectionChip('24/7 Security', false),
  SelectionChip('CCTV Cameras', false),
  SelectionChip('Access Control System',false),
  SelectionChip('Temperature Controlled', false),
  SelectionChip('Humidity Controlled', false),
  SelectionChip('Ventilation System', false),
  SelectionChip('Dock Doors', false),
  SelectionChip('Forklift Accessible', false),
  SelectionChip('Drive-in Access', false),
  SelectionChip('High Ceilings', false),
  SelectionChip('Pallet Racking', false),
  SelectionChip('Shelving Units', false),
];
final List<SelectionChip> eventAmenitiesConstant = [
  SelectionChip('Stage', false),
  SelectionChip('Audio/Visual Equipment', false),
  SelectionChip('Lighting System', false),
  SelectionChip('Retractable Seating', false),
  SelectionChip('Movable Walls', false),
  SelectionChip('Catering Kitchen', false),
  SelectionChip('Restrooms', false),
  SelectionChip('Break Out Areas', false),
  SelectionChip('High-Speed Wi-Fi', false),
  SelectionChip('Projector and Screen', false),
  SelectionChip('Business Center', false),
];
final List<SelectionChip> commercialAmenitiesConstant = [
  SelectionChip('Elevator Access', false),
  SelectionChip('Handicap Accessible', false),
  SelectionChip('Fire Safety', false),
  SelectionChip('Alarm System', false),
  SelectionChip('Energy Efficiency', false),
  SelectionChip('Security Systems', false),
  SelectionChip('Emergency Exits', false),
  SelectionChip('Lobby/Reception Area', false),
];
