name: oprs
description: "An Online Property Rental App, A Final Project."
publish_to: 'None'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  flutter_svg: ^2.0.6
  cached_network_image: ^3.3.1
  email_validator: ^2.0.1
  carousel_slider: ^4.2.1
  flutter_masonry_view: ^0.0.2
  flutter_rating_bar: ^4.0.1
  easy_image_viewer: ^1.4.1
  image_picker: ^0.8.7
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.1
  permission_handler: ^11.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  calendar_date_picker2: ^0.5.6
  flutter_xlider: ^3.5.0
  flutter_secure_storage: ^8.1.0
  table_calendar: ^3.1.2
  http_parser: ^4.0.2
  timeago: ^3.6.1
  intl: ^0.19.0
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700